stages:
  - build
  - docker_tag
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: none
  DOCKER_IMAGE_DOC: $CI_REGISTRY_IMAGE/doc
  DOCKERHUB_IMAGE_DOC: vikyai/doc

image: vikyai/tools-gitlab-auto-deploy-image:latest
before_script:
  - if [ "${TRACE:-false}" == "true" ] ; then  set -x ; fi
  # load auto-deploy if exits (not in test)
  - if [ -f /auto-deploy.sh ] ; then . /auto-deploy.sh ; fi

.kubernetes_runner:
  tags:
    - kubernetes
  variables:
    CI_SERVICE_HOST: "127.0.0.1"

# Build docker image
build_doc:
  extends: .kubernetes_runner
  stage: build
  script:
    - docker_build ${DOCKER_IMAGE_DOC} .

# Tag docker image to lasted
tag_latest:
  extends: .kubernetes_runner
  stage: docker_tag
  variables:
    GIT_STRATEGY: none
  only:
    refs:
      - master
  except:
    refs:
      - tags
  script:
    - docker_tag_latest ${DOCKER_IMAGE_DOC}

# Push Docker image to Dockerhub only when on Master and it's a Tag
.push_dockerhub:
  extends: .kubernetes_runner
  stage: docker_tag
  environment:
    name: viky-ai-production
  script:
    - export VIKY_GITLAB_TAG="${CI_COMMIT_REF_SLUG:-latest}"
    - docker_push_gitlab_to_dockerhub "${DOCKER_IMAGE_DOC}:${VIKY_GITLAB_TAG}"          "${DOCKERHUB_IMAGE_DOC}:${VIKY_DOCKERHUB_TAG}"

push_dockerhub_master:
  extends: .push_dockerhub
  stage: docker_tag
  only:
    refs:
      - master
    variables:
      - $DOCKER_HUB_LOGIN
      - $DOCKER_HUB_PASSWORD
  variables:
    VIKY_DOCKERHUB_TAG: "latest"
  environment:
    name: viky-ai-production

push_dockerhub_tag:
  extends: .push_dockerhub
  stage: docker_tag
  only:
    refs:
      - tags
    variables:
      - $DOCKER_HUB_LOGIN
      - $DOCKER_HUB_PASSWORD
  variables:
    VIKY_DOCKERHUB_TAG: ${CI_COMMIT_TAG}
  environment:
    name: viky-ai-production

push_dockerhub_saas:
  extends: .push_dockerhub
  stage: docker_tag
  only:
    refs:
      - saas
    variables:
      - $DOCKER_HUB_LOGIN
      - $DOCKER_HUB_PASSWORD
  variables:
    VIKY_DOCKERHUB_TAG: "saas"

deploy_dev:
  extends: .kubernetes_runner
  only:
    variables:
      - $DEPLOY_GITLAB_CI_URL_DEV_B64
  except:
    refs:
      - saas
      - tags
  environment:
    name: dev-website-${CI_COMMIT_REF_SLUG}
    url: https://viky-website-${CI_ENVIRONMENT_SLUG}-kube.viky.ai
    # TODO trigger auto delete env with api env stop : https://docs.gitlab.com/ee/api/environments.html#stop-an-environment
    #on_stop: delete_env
  extends: .kubernetes_runner
  stage: deploy
  script:
    - |
      # Deploy to dev
      export DOCKER_IMAGE_DOC_TAG="${CI_COMMIT_REF_SLUG}"
      if [ "${DOCKER_IMAGE_DOC_TAG}" == "master" ] ; then DOCKER_IMAGE_DOC_TAG="latest" ; if
      export DEPLOY_GITLAB_CI_URL=$(echo "${DEPLOY_GITLAB_CI_URL_DEV_B64}" | base64 -d)
      curl --show-error --silent --output /dev/null -X POST \
      -F token=${DEPLOYMENT_TOKEN_DEV} \
      -F ref=master \
      -F variables[VIKY_DEPLOY_NAME]=website-${CI_COMMIT_REF_SLUG} \
      -F variables[VIKY_DOCKER_TAG]=${VIKY_DOCKER_TAG:-latest} \
      -F variables[DOCKER_IMAGE_DOC_TAG]=${DOCKER_IMAGE_DOC_TAG} \
      -F variables[NOTIFY_DEPLOYMENT_INFO]=${CI_COMMIT_SHORT_SHA} \
      "${DEPLOY_GITLAB_CI_URL}"

deploy_production:
  extends: .kubernetes_runner
  only:
    refs:
      - saas
    variables:
      - $DEPLOY_GITLAB_CI_URL_PROD_B64
  except:
    refs:
      - tags
  environment:
    name: viky-ai-production
    url: https://www.viky.ai
  stage: deploy
  script:
    - |
      # Deploy to production
      export DEPLOY_GITLAB_CI_URL=$(echo "${DEPLOY_GITLAB_CI_URL_PROD_B64}" | base64 -d)
      curl --show-error --silent --output /dev/null -X POST \
      -F token=${DEPLOYMENT_TOKEN_PROD} \
      -F ref=master \
      -F variables[VIKY_DEPLOY_NAME]=viky-ai-production \
      -F variables[VIKY_DOCKER_TAG]=saas \
      -F variables[DOCKER_IMAGE_DOC_TAG]=saas \
      -F variables[NOTIFY_DEPLOYMENT_INFO]=${CI_COMMIT_SHORT_SHA} \
      "${DEPLOY_GITLAB_CI_URL}"
